alope/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('alopehomeapp.urls')),
    path('movies/', include('movies.urls')),
    path('music/', include('music.urls')),
    path('sports/', include('sports.urls')),
    path('news/', include('news.urls')),
    path('weather/', include('weather.urls')),
]

music/urls.py
from django.urls import path
from . import views
from django.urls import re_path

urlpatterns = [
    path('songs/', views.songs, name="songs"),
    re_path("song/", views.SongApiView.as_view()),
    path('country/', views.country, name='country'),
    path("jazz/", views.jazz, name="jazz"),
    path("hiphop/", views.hiphop, name="hiphop"),
    path("reggae/", views.reggae, name="reggae"),
    path("rock/", views.rock, name="rock"),
    path("gospel/", views.gospel, name="gospel"),
    path("rnb/", views.rnb, name="rnb"),
    path("pop/", views.pop, name="pop"),
    path("electronic/", views.electronic, name="electronic"),
    

]

news/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('news_page/', views.news_page, name="news_page")
]

music/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name
    
class Music(models.Model):
    category_name = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=50, null=True, blank=True)
    artist = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.title
    

music/forms.py
from django import forms

class MusicSearchForm(forms.Form):
    search_query = forms.CharField(required=False, label='Search Music')

music/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response
from . models import *
from . serializers import *


# dealing with the search form for music
from django.db.models import Q
from . forms import MusicSearchForm
# Create your views here.

# This is for the music search query
def music_list(request):
    
    queryset = Music.objects.all()
    search_form = MusicSearchForm(request.GET)

    if search_form.is_valid():
        search_query = search_form.cleaned_data.get('search_query')
        if search_query:
            queryset = queryset.filter(Q(title__icontains=search_query) | Q(artist__icontains=search_query))

    context = {
        'object_list': queryset,
        'search_form':search_form
    }

    return render(request, 'products/music.html', context, )



class SongApiView(APIView):
    serializer_class = PopSerializer
    def get(self, request):
        all_songs = Music.objects.all().values()
        return Response({"Message":"List of Songs","Song List":all_songs})

    
    def post(self, request):
        print('Request data is : ', request.data)
        serializer_obj = PopSerializer(data=request.data)

        if (serializer_obj.is_valid()):

            Music.objects.create(id=serializer_obj.data.get("id"), 
                            title=serializer_obj.data.get("title"), 
                            artist=serializer_obj.data.get("artist"),)

        song = Music.objects.all().filter(id=request.data["id"]).values()
        return Response({"Message":"New Song Added!","Song":song})


def songs(request):
    return render(request, 'products/music.html')

def country(request):
    return render(request, 'products/songs/country.html')

def gospel(request):
    return render(request, 'products/songs/gospel.html')

def hiphop(request):
    return render(request, 'products/songs/hip_hop.html')

def jazz(request):
    return render(request, 'products/songs/jazz.html')

def pop(request):
    return render(request, 'products/songs/pop.html')

def rnb(request):
    return render(request, 'products/songs/rnb.html')

def rock(request):
    return render(request, 'products/songs/rock.html')

def reggae(request):
    return render(request, "products/songs/reggae.html")

def electronic(request):
    return render(request, "products/songs/electronic.html")

music/templates/products/music.html
{% extends 'base.html' %}
{% block content %}
    <h1>Music Loading...</h1>

    <form method="get" action="">
        {% csrf_token %}

        <div class="form-group">
            <input type="text">
            <label for="id_search_query">Search:</label>
            {{ search_form.search_query }}
        </div>
        
        <button type="submit" class="btn btn-primary">Search</button>
    </form>
    
    {% for item in object_list %}
    <!-- Displaying model items here -->
        {{ item.title }}
        {{  item.artist }}

    {% endfor %}
    
    <nav>
        <li><a href="{% url 'rock' %}">Rock</a></li>
        <li><a href="{% url 'pop' %}">Pop</a></li>
        <li><a href="{% url 'country' %}">Country</a></li>
        <li><a href="{% url 'jazz' %}">Jazz</a></li>
        <li><a href="{% url 'hiphop' %}">Hip Hop</a></li>
        <li><a href="{% url 'rnb' %}">RnB</a></li>
        <li><a href="{% url 'gospel' %}">Gospel</a></li>
        <li><a href="{% url 'reggae' %}">Reggae</a></li>
    </nav>

    
   
        
{% endblock %}